/**
 * EXIF/XMP Metadata Analyzer
 * Extracts and analyzes image metadata for AI generation indicators
 */

import exifr from 'exifr';
import type { MetadataResult } from '../types';

/**
 * Known AI tool identifiers (case-insensitive matching)
 */
const AI_TOOL_PATTERNS = [
  // Stable Diffusion ecosystem
  'stable diffusion',
  'stability.ai',
  'stability ai',
  'automatic1111',
  'a1111',
  'comfyui',
  'comfy ui',
  'invoke ai',
  'invokeai',
  'diffusers',
  'sd webui',
  'sdxl',
  'sd 1.5',
  'sd 2.1',
  
  // Midjourney
  'midjourney',
  'mj',
  
  // DALL-E / OpenAI
  'dall-e',
  'dall·e',
  'dalle',
  'openai',
  'chatgpt',
  
  // Adobe Firefly
  'firefly',
  'adobe firefly',
  
  // Google
  'imagen',
  'google ai',
  
  // Other AI tools
  'leonardo.ai',
  'leonardo ai',
  'nightcafe',
  'artbreeder',
  'runway',
  'runwayml',
  'dream studio',
  'dreamstudio',
  'bing image creator',
  'copilot designer',
  'ai generated',
  'ai-generated',
  'generated by ai',
  'flux',
  'flux.1',
  
  // Generic AI indicators
  'text-to-image',
  'text2img',
  'txt2img',
  'img2img',
  'inpainting',
  'controlnet',
  'lora',
  'checkpoint',
  'sampler',
  'cfg scale',
  'negative prompt',
  'denoising',
];

/**
 * Check if a string contains AI-related indicators
 */
function findAIIndicators(value: string): string[] {
  if (!value || typeof value !== 'string') return [];
  
  const lowerValue = value.toLowerCase();
  const found: string[] = [];
  
  for (const pattern of AI_TOOL_PATTERNS) {
    if (lowerValue.includes(pattern.toLowerCase())) {
      found.push(pattern);
    }
  }
  
  return found;
}

/**
 * Extract string value from potentially complex EXIF field
 */
function extractStringValue(value: unknown): string | undefined {
  if (typeof value === 'string') return value;
  if (typeof value === 'number') return String(value);
  if (Array.isArray(value)) return value.join(', ');
  if (value && typeof value === 'object') {
    // Handle objects with description or value properties
    const obj = value as Record<string, unknown>;
    if ('description' in obj) return String(obj.description);
    if ('value' in obj) return String(obj.value);
  }
  return undefined;
}

/**
 * Analyze image metadata for AI generation indicators
 */
export async function analyzeMetadata(data: ArrayBuffer): Promise<MetadataResult> {
  try {
    // Parse all available metadata
    const metadata = await exifr.parse(data, {
      // Enable all parsers
      tiff: true,
      xmp: true,
      icc: true,
      iptc: true,
      jfif: true,
      ihdr: true,
      // Get these specific tags
      pick: [
        'Software',
        'Artist',
        'Make',
        'Model',
        'Creator',
        'CreatorTool',
        'Description',
        'ImageDescription',
        'UserComment',
        'Copyright',
        'XPComment',
        'XPAuthor',
        'XPSubject',
        'XPKeywords',
        'XPTitle',
        'HistorySoftwareAgent',
        'HistoryAction',
      ],
      // Also get all other fields for thorough analysis
      translateKeys: true,
      translateValues: true,
      reviveValues: true,
    });

    if (!metadata) {
      return {
        found: false,
        aiIndicators: [],
      };
    }

    // Extract key fields
    const software = extractStringValue(metadata.Software);
    const artist = extractStringValue(metadata.Artist || metadata.Creator);
    const make = extractStringValue(metadata.Make);
    const model = extractStringValue(metadata.Model);
    const creatorTool = extractStringValue(metadata.CreatorTool);
    
    // Collect all string values for AI indicator search
    const allValues: string[] = [];
    const rawFields: Record<string, unknown> = {};
    
    for (const [key, value] of Object.entries(metadata)) {
      const strValue = extractStringValue(value);
      if (strValue) {
        allValues.push(strValue);
        rawFields[key] = strValue;
      }
    }

    // Find AI indicators across all metadata
    const aiIndicators: string[] = [];
    const seenIndicators = new Set<string>();
    
    for (const value of allValues) {
      const indicators = findAIIndicators(value);
      for (const indicator of indicators) {
        const lowerIndicator = indicator.toLowerCase();
        if (!seenIndicators.has(lowerIndicator)) {
          seenIndicators.add(lowerIndicator);
          aiIndicators.push(indicator);
        }
      }
    }

    return {
      found: true,
      software,
      artist,
      make,
      model,
      creatorTool,
      aiIndicators,
      rawFields: Object.keys(rawFields).length > 0 ? rawFields : undefined,
    };
  } catch (err) {
    // Many images have no EXIF data - this is not an error
    return {
      found: false,
      aiIndicators: [],
    };
  }
}

